### ISSUE TITLE
Comparison of two graphs gives not implemented for directed type graph exception

### ISSUE THREAD

**Issue by shubham-scisar** [CosmiQ/apls#17]
I am calculating apls metric for comparison of two geojson's and getting this error : 

```
Traceback (most recent call last):
  File "apls.py", line 3690, in <module>
    main()
  File "apls.py", line 3661, in main
    super_verbose=super_verbose)
  File "apls.py", line 2552, in gather_files
    verbose=verbose)
  File "apls.py", line 998, in _create_gt_graph
    super_verbose=super_verbose)
  File "apls.py", line 1227, in _refine_gt_graph
    verbose=verbose, super_verbose=super_verbose)
  File "apls.py", line 909, in _clean_sub_graphs
    sub_graphs = list(nx.connected_component_subgraphs(G_))
  File "C:\Users\xyz\Anaconda3\envs\apls_new\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\xyz\Anaconda3\envs\apls_new\lib\site-packages\networkx\utils\decorators.py", line 80, in _not_implemented_for
    raise nx.NetworkXNotImplemented(msg)
networkx.exception.NetworkXNotImplemented: not implemented for directed type

```

**Comment by vvangfaye** [comment]
same question
