### ISSUE TITLE
Fail to read geojson file

### ISSUE THREAD

**Issue by LokLu** [CosmiQ/apls#5]
I run the create_masks.py to generate masks for paris images.
It went wrong when came to img377 as following error info.
It worked with previous few images only down when dealing with img377.

Any idea about that?
Thank you!

name_root: img377
  output_raster: /media/lok/dataset/lok/data/spacenet/road/data/AOI_3_Paris_Roads_Train/masks_2m/mask_img377.png
  output_plot_file: /media/lok/dataset/lok/data/spacenet/road/data/AOI_3_Paris_Roads_Train/masks_2m_plots/mask_img377.png
geojsonfilename = /media/lok/dataset/lok/data/spacenet/road/data/AOI_3_Paris_Roads_Train/geojson/spacenetroads/spacenetroads_AOI_3_Paris_img377.geojson
Traceback (most recent call last):
  File "create_spacenet_masks.py", line 112, in <module>
    main()
  File "create_spacenet_masks.py", line 107, in main
    verbose=False)
  File "/media/lok/dataset/lok/data/spacenet/road/apls/src/apls_tools.py", line 432, in get_road_buffer
    projectToUTM=True)
  File "/media/lok/dataset/lok/data/spacenet/road/apls/src/apls_tools.py", line 329, in create_buffer_geopandas
    inGDF = gpd.read_file(geoJsonFileName)
  File "/home/lok/anaconda2/envs/apls_environment/lib/python2.7/site-packages/geopandas/io/file.py", line 19, in read_file
    with fiona.open(filename, **kwargs) as f:
  File "/home/lok/anaconda2/envs/apls_environment/lib/python2.7/site-packages/fiona/__init__.py", line 165, in open
    enabled_drivers=enabled_drivers)
  File "/home/lok/anaconda2/envs/apls_environment/lib/python2.7/site-packages/fiona/collection.py", line 153, in __init__
    self.session.start(self)
  File "fiona/ogrext.pyx", line 405, in fiona.ogrext.Session.start
  File "fiona/_err.pyx", line 185, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_OpenFailedError: Failed to read GeoJSON data

**Comment by avanetten** [comment]
That issue is caused by an empty geojson file.  apls_tools.py is now updated to handle such files.
